#!/usr/bin/env python3
"""Generate the Android launcher icons from the same bands as terminal/make-icons.py (stdlib only).

Writes the adaptive-icon foreground as a vector drawable (Android 8+) and legacy
square/round PNGs for Android 7.
"""
import struct, zlib
from pathlib import Path

BG = (0x0a, 0x13, 0x22)
# (top, height, left, right) in units of a 100x100 canvas, colour. Keep in sync with terminal/make-icons.py.
BANDS = [
    ((22, 6, 18, 62), (0x16, 0x3e, 0x78)),
    ((31, 7, 18, 74), (0x12, 0x80, 0x96)),
    ((41, 8, 18, 82), (0xec, 0xb0, 0x48)),
    ((52, 7, 18, 68), (0xff, 0xf6, 0xde)),
    ((62, 6, 18, 56), (0x7f, 0xdc, 0xb8)),
    ((71, 6, 18, 44), (0xf2, 0xb8, 0x4b)),
]
LEGACY = {'mdpi': 48, 'hdpi': 72, 'xhdpi': 96, 'xxhdpi': 144, 'xxxhdpi': 192}

def render(n, round_mask=False):
    s = n / 100
    px = [[BG] * n for _ in range(n)]
    for (top, h, l, r), col in BANDS:
        for y in range(round(top * s), round((top + h) * s)):
            for x in range(round(l * s), round(r * s)):
                px[y][x] = col
    rgba = []
    for y, row in enumerate(px):
        out = []
        for x, p in enumerate(row):
            inside = not round_mask or (x + .5 - n / 2) ** 2 + (y + .5 - n / 2) ** 2 <= (n / 2) ** 2
            out.append(p + ((255,) if inside else (0,)))
        rgba.append(out)
    return rgba

def png(px):
    n = len(px)
    raw = b''.join(b'\0' + bytes(c for p in row for c in p) for row in px)
    chunk = lambda t, d: struct.pack('>I', len(d)) + t + d + struct.pack('>I', zlib.crc32(t + d))
    return (b'\x89PNG\r\n\x1a\n'
            + chunk(b'IHDR', struct.pack('>IIBBBBB', n, n, 8, 6, 0, 0, 0))
            + chunk(b'IDAT', zlib.compress(raw, 9))
            + chunk(b'IEND', b''))

def vector():
    # 100-unit canvas -> 108dp viewport; the 40-unit maskable radius lands on the 33dp adaptive safe zone.
    s = 0.825
    t = 54 - 50 * s
    paths = '\n'.join(
        f'        <path android:fillColor="#{r:02X}{g:02X}{b:02X}" android:pathData="M{x0},{top}h{x1 - x0}v{h}h{x0 - x1}z"/>'
        for (top, h, x0, x1), (r, g, b) in BANDS)
    return f'''<?xml version="1.0" encoding="utf-8"?>
<!-- Generated by app/scripts/make-android-icons.py -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <group android:scaleX="{s}" android:scaleY="{s}" android:translateX="{t}" android:translateY="{t}">
{paths}
    </group>
</vector>
'''

res = Path(__file__).resolve().parent.parent / 'android/app/src/main/res'
for d, n in LEGACY.items():
    (res / f'mipmap-{d}/ic_launcher.png').write_bytes(png(render(n)))
    (res / f'mipmap-{d}/ic_launcher_round.png').write_bytes(png(render(n, True)))
    (res / f'mipmap-{d}/ic_launcher_foreground.png').unlink(missing_ok=True)
(res / 'drawable-v24/ic_launcher_foreground.xml').unlink(missing_ok=True)
(res / 'drawable/ic_launcher_foreground.xml').write_text(vector())
